configuration: Release
version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
artifacts:
  - path: 'src\**\*.nupkg'
  
init:
  - git config --global core.autocrlf true
  
before_build:
- ps: invoke-webrequest https://go.microsoft.com/fwlink/?LinkID=827524 -OutFile core.exe
- ps: .\core.exe /install /quiet /norestart
- ps: iwr -Uri https://download.microsoft.com/download/E/F/D/EFD52638-B804-4865-BB57-47F4B9C80269/NDP462-DevPack-KB3151934-ENU.exe -OutFile net452.exe
- ps: start-process .\net452.exe -Wait '/install /quiet /norestart'

build_script:
- ps: dotnet restore
- ps: dotnet build -c Release .\src\UriBuilder.Fluent
- ps: dotnet publish -c Release .\src\UriBuilder.Fluent.UnitTests


test_script:
- ps: dotnet test -c Release .\src\UriBuilder.Fluent.UnitTests
- ps: .\Coverage.ps1
- ps: .\update-projectjson.ps1
- ps: dotnet restore
- ps: dotnet pack -c Release .\src\UriBuilder.Fluent

deploy:
- provider: NuGet
  api_key:
    secure: QuVcKEvDkLsmdemVpoGBXiTymN46CzvczrDpTHNf1+tTIjOGufptGDmBD9r5LVtn
  on:
    appveyor_repo_tag: true