image: Visual Studio 2017
configuration: Release
version: 1.0.{build}
artifacts:
- path: output\**.nupkg
  
init:
  - git config --global core.autocrlf true

build_script:
- ps: >-
    dotnet restore UriBuilder.Fluent.sln --source https://api.nuget.org/v3/index.json
        dotnet build UriBuilder.Fluent.sln
        if($env:APPVEYOR_REPO_TAG -eq "true")
        {
          dotnet pack src\UriBuilder.Fluent\UriBuilder.Fluent.csproj --configuration Release --output ..\..\output /p:Version=$env:APPVEYOR_REPO_TAG_NAME
        }


test_script:
- ps: dotnet clean
- ps: dotnet build /p:DebugType=full
- ps: dotnet test .\src\UriBuilder.Fluent.UnitTests\UriBuilder.Fluent.UnitTests.csproj --no-build
- ps: .\Coverage.ps1

deploy:
- provider: NuGet
  api_key:
    secure: QuVcKEvDkLsmdemVpoGBXiTymN46CzvczrDpTHNf1+tTIjOGufptGDmBD9r5LVtn
  on:
    appveyor_repo_tag: true