image: Visual Studio 2017
configuration: Release
version: 1.0.{build}
artifacts:
  - path: 'src\**\*.nupkg'
  
init:
  - git config --global core.autocrlf true
  
before_build:
- ps: invoke-webrequest https://go.microsoft.com/fwlink/?LinkID=827524 -OutFile core.exe
- ps: .\core.exe /install /quiet /norestart

build_script:
- ps: >-
    dotnet restore HardHat.sln --source https://api.nuget.org/v3/index.json
        dotnet build HardHat.sln
        if($env:APPVEYOR_REPO_TAG -eq "true")
        {
          dotnet pack src\HardHat\HardHat.csproj --configuration Release --output ..\..\output /p:Version=$env:APPVEYOR_REPO_TAG_NAME
        }


test_script:
- ps: dotnet test -c Release .\src\UriBuilder.Fluent.UnitTests\UriBuilder.Fluent.UnitTests.csproj
- ps: .\Coverage.ps1

deploy:
- provider: NuGet
  api_key:
    secure: QuVcKEvDkLsmdemVpoGBXiTymN46CzvczrDpTHNf1+tTIjOGufptGDmBD9r5LVtn
  on:
    appveyor_repo_tag: true