image: Visual Studio 2022
configuration: Release
version: 7.0.{build}
artifacts:
- path: output\**.nupkg
  
init:
  - git config --global core.autocrlf true

build_script:
- ps: >-
    dotnet restore UriBuilder.Fluent.sln --source https://api.nuget.org/v3/index.json
        dotnet build UriBuilder.Fluent.sln --configuration Release
        if($env:APPVEYOR_REPO_TAG -eq "true")
        {
          dotnet pack src\UriBuilder.Fluent\UriBuilder.Fluent.csproj --configuration Release --output ..\..\output /p:Version=$env:APPVEYOR_REPO_TAG_NAME
        }


test_script:
- ps: dotnet test -c Release .\src\UriBuilder.Fluent.UnitTests\UriBuilder.Fluent.UnitTests.csproj

deploy:
- provider: NuGet
  api_key:
    secure: //tKHlb2yqAtpxnR6p9IAtXwQNaq8UYYyIFSD0QVF3XnEasIxG2gTWdmWuG87fUX
  on:
    appveyor_repo_tag: true